<?php return array (
  'site_name' => 'AFROPHP Framework',
	'uri_protocol' => 'REQUEST_URI',
	'enable_query_strings' => false,
	'controller_trigger' => 'q',
	'language' => 'en',
	'charset' => 'UTF-8',
	'display_errors' => 1,
	'error_reporting' => E_ALL,
	'log_threshold' => '2',
	'default_timezone' => 'UTC',
	'csrf_protection' => 0,
  'autohtaccess' => false,
	'profiling' => 0,
  'front_theme' => 'default',
  'back_theme' => 'gentele',
  'admin_path' => 'admin',
  'script_version' => '2',
	'style_version' => '1',
	'cache_time' => 0,
  //cookie configuration
  'cookie'=>['prefix' => '',
  	'domain' => '',
  	'path' => '/',
  	'secure' => false,
  	'httponly' => false,
  ],
  //exception configuration
  'exception'=>[
    'sender_name' => 'AFROPHP',
    'sender_email' => 'exception@afrophp.com',
    'subject' => 'Error Type: {level}',
    'recipients' => ['diltony@yahoo.com','diltony@gmail.com'],
    'mailer_enabled' => false,
    'enable_stack_trace' => true,
    'show_error' => true,
  ],
  //database configuration
  'dbase'=>[
    'dsn'=>'',
    'driver' => 'mysql',
    'hostname' => 'localhost',
    'username' => 'admin',
    'password' => 'pass',
    'name' => 'afrophp',
    'port' => null,
    'char_set' => 'utf8',
    'collat' => 'utf8_general_ci',
    'prefix' => 'afro_',
    'schema'=>'public',
    'persistent'=>true,
  ],
  //session configuration
  'session'=>[
    'handler' => 'dbase',
  	'match_ip' => false,
  	'match_fingerprint' => false,
  	'match_token' => false,
  	'table' => 'session',
  	'name' => 'afro_session',
  	'id' => null,
  	'cookie_path' => null,
  	'cookie_secure' => null,
  	'cookie_regenerate' => 300,
  	'expiration' => 7200,
  	'gc_probability' => 100,
  ],
  //email settings
  'email'=>[
    'smtp_host' => 'smtp.gmail.com',
  	'smtp_username' => 'diltony@gmail.com',
  	'smtp_password' => 'xxx',
  	'smtp_port' => 465,
  	'smtp_secure' => 'ssl',
  	'smtp_enabled' => 0,
  	'send_enabled' => 1,
  ],
);
